### ISSUE TITLE
v1.0.0 todo

### ISSUE THREAD

**Issue by jmeas** [jmeas/react-request#96]
What do I want to see before I push for a 1.0.0 release?

- [x] Look into the code, and possibly refactor it to clean things up ( #84 )
- [x] Document all of the exports ( #85 )
- [x] Review documentation to make sure that it's 👌 
- [x] Make sure that the build is good to go
